-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 01:49:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kronos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kronos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kronos` DEFAULT CHARACTER SET utf8 ;
USE `kronos` ;

-- -----------------------------------------------------
-- Table `kronos`.`m_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kronos`.`m_department` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `path` VARCHAR(1000) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kronos`.`m_workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kronos`.`m_workers` (
  `id` BIGINT NOT NULL,
  `worker_number` VARCHAR(20) NOT NULL,
  `family_name` VARCHAR(50) NULL,
  `first_name` VARCHAR(50) NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `mail_address` VARCHAR(200) NULL,
  `birth_day` DATETIME NULL,
  `m_department_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_m_workers_m_department_idx` (`m_department_id` ASC),
  CONSTRAINT `fk_m_workers_m_department`
    FOREIGN KEY (`m_department_id`)
    REFERENCES `kronos`.`m_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kronos`.`m_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kronos`.`m_projects` (
  `id` BIGINT NOT NULL,
  `no` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `m_account_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`no` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kronos`.`m_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kronos`.`m_orders` (
  `id` BIGINT NOT NULL,
  `no` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `m_projects_id` BIGINT NOT NULL,
  `m_client_id` BIGINT NULL,
  `sales_kind` INT NOT NULL COMMENT '1:生産\n2:非生産',
  `estimate_worker_hours` DECIMAL(8,2) NULL COMMENT '見積作業時間',
  `order_worker_hours` DECIMAL(8,2) NULL,
  `order volume` BIGINT NULL,
  `receiving_inspection_date` VARCHAR(45) NULL COMMENT '検収(予定)日',
  `status` INT NULL COMMENT '1:見積\n2:仮受注\n3:受注\n4:納品\n5:検収',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`no` ASC),
  INDEX `fk_m_orders_m_projects1_idx` (`m_projects_id` ASC),
  CONSTRAINT `fk_m_orders_m_projects1`
    FOREIGN KEY (`m_projects_id`)
    REFERENCES `kronos`.`m_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kronos`.`t_order_work_breakdowns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kronos`.`t_order_work_breakdowns` (
  `id` BIGINT NOT NULL,
  `m_orders_id` BIGINT NOT NULL,
  `work_name` VARCHAR(20) NOT NULL COMMENT '作業項目名',
  `estimate_worker_hours` DECIMAL(5,2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_worked_hours_m_orders1_idx` (`m_orders_id` ASC),
  CONSTRAINT `fk_t_worked_hours_m_orders10`
    FOREIGN KEY (`m_orders_id`)
    REFERENCES `kronos`.`m_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kronos`.`t_worked_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kronos`.`t_worked_hours` (
  `id` BIGINT NOT NULL,
  `m_workers_id` BIGINT NOT NULL,
  `m_orders_id` BIGINT NOT NULL,
  `t_order_work_breakdowns_id` BIGINT NULL,
  `work_day` DATETIME NULL,
  `work_hours` DECIMAL(5,2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_worked_hours_m_workers1_idx` (`m_workers_id` ASC),
  INDEX `fk_t_worked_hours_m_orders1_idx` (`m_orders_id` ASC),
  INDEX `fk_t_worked_hours_t_order_work_breakdowns1_idx` (`t_order_work_breakdowns_id` ASC),
  CONSTRAINT `fk_t_worked_hours_m_workers1`
    FOREIGN KEY (`m_workers_id`)
    REFERENCES `kronos`.`m_workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_worked_hours_m_orders1`
    FOREIGN KEY (`m_orders_id`)
    REFERENCES `kronos`.`m_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_worked_hours_t_order_work_breakdowns1`
    FOREIGN KEY (`t_order_work_breakdowns_id`)
    REFERENCES `kronos`.`t_order_work_breakdowns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
